// Generated by RPG Maker MZ - Plugin Configuration
// Pokemon Madrid: Edición Castiza
// Minimal plugin configuration to allow game to boot

var $plugins = [
  // Todos los plugins deshabilitados temporalmente para debugging
  // El juego cargará con funcionalidad básica de RPG Maker MZ
];
