// Generated by RPG Maker MZ - Plugin Configuration
// Pokemon Madrid: Edición Castiza

var $plugins = [
  // ========================================
  // CORE POKEMON SYSTEM - Monster Capture
  // ========================================
  {
    "name": "Synrec_MC_Core",
    "status": true,
    "description": "Monster Capture Core - Permite capturar enemigos y convertirlos en aliados",
    "parameters": {
      "captureFormula": "((3 * a.mhp - 2 * a.hp) * a.catchRate * b) / (3 * a.mhp)",
      "captureVariable": "1",
      "capturedSwitch": "1"
    }
  },
  {
    "name": "Synrec_MC_BattleCore",
    "status": true,
    "description": "Monster Capture Battle Core - Sistema de batalla para captura de monstruos",
    "parameters": {}
  },
  {
    "name": "Synrec_MC_Evolution",
    "status": true,
    "description": "Monster Capture Evolution - Sistema de evolución de criaturas",
    "parameters": {
      "evolutionSwitch": "2"
    }
  },
  {
    "name": "Synrec_MC_Beastiary",
    "status": true,
    "description": "Monster Capture Beastiary - Pokédex/Bestiario de criaturas capturadas",
    "parameters": {}
  },
  {
    "name": "Synrec_MC_GenderTraits",
    "status": true,
    "description": "Monster Capture Gender Traits - Género de criaturas con traits especiales",
    "parameters": {}
  },
  {
    "name": "Synrec_MC_PlayerSetup",
    "status": true,
    "description": "Monster Capture Player Setup - Configuración inicial del jugador",
    "parameters": {}
  },

  // ========================================
  // POKEMON MECHANICS - SumRndmDde
  // ========================================
  {
    "name": "SRD_PokemonTypeSystem",
    "status": true,
    "description": "Pokemon Type System - Sistema de tipos con super-efectivo y no muy efectivo",
    "parameters": {
      "typeChart": "default"
    }
  },
  {
    "name": "SRD_PokemonTypeDisplay",
    "status": true,
    "description": "Pokemon Type Display - Muestra los tipos del Pokemon en la UI",
    "parameters": {}
  },
  {
    "name": "SRD_Natures",
    "status": true,
    "description": "Natures - Sistema de naturalezas que afectan stats de Pokemon",
    "parameters": {}
  },
  {
    "name": "SRD_Pokemon4MovesOnly",
    "status": true,
    "description": "Pokemon 4 Moves Only - Limita movimientos a máximo 4 por Pokemon",
    "parameters": {
      "maxMoves": "4"
    }
  }
];
