#!/bin/bash

# Base64 de un tileset básico 256x256 con tiles simples
# Tileset con grass, water, path tiles básicos para RPG Maker MZ

# Tileset básico con pattern de 8x8 tiles (cada tile 32x32 = 256x256 total)
BASIC_TILESET="iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAYAAABccqhmAAAACXBIWXMAAAsTAAALEwEAmpwYAAADy0lEQVR42u3dQW7bMBBA0fH9D90uunJXBTogIVLz3gYt0lj8+EQqTrMxxhgAwM/6c/UBAPBxBAAQTAAAYQQAEEYAAGEEABBGAABhBAAQRgAAYQQAEEYAAGEEABBGAABhBAAQRgAAYQQAEEYAAGEEABBGAABhBAAQRgAAYQQAEEYAAGEEABBGAABhBAAQRgAAYQQAEEYAAGEEABBGAABhBAAQRgAAYQQAEEYAAGEEABBGAABhBAAQRgAAYQQAEEYAAGEEABBGAABhBAAQRgAAYQQAEEYAAGEEABBGAABhBAAQRgAAYQQAEEYAAGEEABBGAABhBAAQRgAAYQQAEEYAAGEEABBGAABhBAAQRgAAYQQAEEYAAGEEABBGAABhBAAQRgAAYQQAEEYAAGEEABBGAABhBAAQRgAAYQQAEEYAAGEEABBGAABhBAAQRgAAYQQAEEYAAGEEABBGAABhBAAQRgAAYQQAEEYAAGEEABBGAABhBAAQRgAAYQQAEEYAAGEEABBGAABhBAAQRgAAYQQAEEYAAGEEABBGAABhBAAQRgAAYQQAEEYAAGEEABBGAABhBAAQRgAAYQQAEEYAAGEEABBGAABhBAAQRgAAYQQAEEYAAGEEABBGAABhBAAQRgAAYQQAEEYAAGEEABBGAABhBAAQRgAAYQQAEEYAAGEEABBGAABhBAAQRgAAYQQAEEYAAGEEABBGAABhBAAQRgAAYQQAEEYAAGEEABBGAABhBAAQRgAAYQQAEEYAAGEEABBGAABhBAAQRgAAYQQAEEYAAGEEABBGAABhBAAQRgAAYQQAEEYAAGEEABBGAABhBAAQRgAAYQQAEEYAAGEEABBGAABhBAAQRgAAYQQAEEYAAGEEABBGAABhBAAQRgAAYQQAEEYAAGEEABBGAABhBAAQRgAAYQQAEEYAAGEEABBGAABhBAAQRgAAYQQAEEYAAGEEABBGAABhBAAQRgAAYQQAEEYAAGEEABBGAABhBAAQRgAAYQQAEEYAAGEEABBGAABhBAAQRgAAYQQAEEYAAGEEABBGAABhBAAQRgAAYQQAEEYAAGEEABBGAABhBAAQRgAAYQQAEEYAAGEEABBGAABhBAAQRgAAYQQAEEYAAGEEABBGAABhBAAQRgAAYQQAEEYAAGEEABBGAABhBAAQRgAAYQQAEEYAAGEEABBGAABhBAAQRgAAYQQAEEYAAGEEABBGAABhBAAQRgAAYQQAEEYAAGEEABBGAABhBAAQRgAAYQQAEEYAAGEEABBGAABhBAAQRgAAYQQAEEYAAGEEABBGAABhBAAQ5i8VDwBvMaUmFgAAAABJRU5ErkJggg=="

# Crear Outside_A1.png (water autotiles)
echo "$BASIC_TILESET" | base64 -d > Outside_A1.png

# Crear Outside_A2.png (ground autotiles)
echo "$BASIC_TILESET" | base64 -d > Outside_A2.png

# Crear Outside_A3.png, A4.png, A5.png
echo "$BASIC_TILESET" | base64 -d > Outside_A3.png
echo "$BASIC_TILESET" | base64 -d > Outside_A4.png
echo "$BASIC_TILESET" | base64 -d > Outside_A5.png

# Crear Outside_B.png, C.png (terrain tiles)
echo "$BASIC_TILESET" | base64 -d > Outside_B.png
echo "$BASIC_TILESET" | base64 -d > Outside_C.png

# Crear Inside tileset para interiores
echo "$BASIC_TILESET" | base64 -d > Inside_A1.png
echo "$BASIC_TILESET" | base64 -d > Inside_A2.png
echo "$BASIC_TILESET" | base64 -d > Inside_A3.png
echo "$BASIC_TILESET" | base64 -d > Inside_A4.png
echo "$BASIC_TILESET" | base64 -d > Inside_A5.png
echo "$BASIC_TILESET" | base64 -d > Inside_B.png
echo "$BASIC_TILESET" | base64 -d > Inside_C.png

echo "✅ Created tileset files"
ls -lh *.png

