#!/bin/bash

# Sprite placeholder genérico
SPRITE="iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAACXBIWXMAAAsTAAALEwEAmpwYAAADHklEQVR42u3dMW7bQBCFYXL/Q3eVrtwVRJHYIrXD/QYQaGz+70nals2yLMsKAL9+//oHAOC3CBAgRAAAQgQAIEQAAEIEACBEAABCBAAgRAAAQgQAIEQAAEIEACBEAABCBAAgRAAAQgQAIEQAAEIEACBEAABCBAAgRAAAQgQAIEQAAEIEACBEAABCBAAgRAAAQgQAIEQAAEIEACBEAABCBAAgRAAAQgQAIEQAAEIEACBEAABCBAAgRAAAQgQAIEQAAEIEACBEAABCBAAgRAAAQgQAIEQAAEIEACBEAABCBAAgRAAAQgQAIEQAAEIEACBEAABCBAAgRAAAQgQAIEQAAEIEACBEAABCBAAgRAAAQgQAIEQAAEIEACBEAABCBAAgRAAAQgQAIEQAAEIEACBEAABCBAAgRAAAQgQAIEQAAEIEACBEAABCBAAgRAAAQgQAIEQAAEIEACBEAABCBAAgRAAAQgQAIEQAAEIEACBEAABCBAAgRAAAQgQAIEQAAEIEACBEAABCBAAgRAAAQgQAIEQAAEIEACBEAABCBAAgRAAAQgQAIEQAAEIEACBEAABCBAAgRAAAQgQAIEQAAEIEACBEAABCBAAgRAAAQgQAIEQAAEIEACBEAABCBAAgRAAAQgQAIEQAAEIEACBEAABCBAAgRAAAQgQAIEQAAEIEACBEAABCBAAgRAAAQgQAIEQAAEIEACBEAABCBAAgRAAAQgQAIEQAAEIEACBEAABCBAAgRAAAQgQAIEQAAEIEACBEAABCBAAgRAAAQgQAIEQAAEIEACBEAABCBAAgRAAAQgQAIEQAAEIEACBEAABCBAAgRAAAQgQAIEQAAEIEACBEAABCBAAgRAAAQgQAIEQAAEIEACBEAABCBAAgRAAAQgQAIEQAAEIEACBEAABCBAAgRAAAQgQAIEQAAEIEACBEAABCBAAgRAAAQgQAIEQAAEIEACBEAABCBAAgRAAAQgQAIEQAAEIEACBEAABCBAAgRAAAQgQAIEQAAEIEACBEAABCBAAgRAAAQgQAIEQAAEIEACBEAABCBAAgRAAAQgQAIEQAAEIEACBEAABC/wDC7gB/gV8qgQAAAABJRU5ErkJggg=="

# SV Actor sprites (side-view battle sprites for player's Pokemon)
cd sv_actors
echo "$SPRITE" | base64 -d > Actor1_1.png
echo "$SPRITE" | base64 -d > Actor1_2.png
echo "$SPRITE" | base64 -d > Actor1_3.png

# SV Enemies (side-view enemy sprites)
cd ../sv_enemies
echo "$SPRITE" | base64 -d > Enemy1.png
echo "$SPRITE" | base64 -d > Enemy2.png

# Battle backgrounds (battlebacks1 = ground, battlebacks2 = sky)
cd ../battlebacks1
echo "$SPRITE" | base64 -d > Grassland.png
echo "$SPRITE" | base64 -d > Road.png
echo "$SPRITE" | base64 -d > Inside.png

cd ../battlebacks2
echo "$SPRITE" | base64 -d > Grassland.png
echo "$SPRITE" | base64 -d > Road.png  
echo "$SPRITE" | base64 -d > Inside.png

# Animations
cd ../animations
echo "$SPRITE" | base64 -d > Fire1.png
echo "$SPRITE" | base64 -d > Water1.png
echo "$SPRITE" | base64 -d > Thunder1.png

# Parallaxes (fondos de mapa)
cd ../parallaxes
echo "$SPRITE" | base64 -d > BlueSky.png

# Pictures
cd ../pictures
echo "$SPRITE" | base64 -d > Picture1.png

# Title screens
cd ../titles1
echo "$SPRITE" | base64 -d > Title.png

cd ../titles2
echo "$SPRITE" | base64 -d > Title2.png

echo "✅ Created all remaining asset files"

